p8105_hw2_jy3270
================
Jingya Yu
2022-10-04

``` r
# load all libraries
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────── tidyverse 1.3.2.9000 ──
    ## ✔ ggplot2   3.3.6      ✔ dplyr     1.0.10
    ## ✔ tibble    3.1.8      ✔ stringr   1.4.1 
    ## ✔ tidyr     1.2.1      ✔ forcats   0.5.2 
    ## ✔ readr     2.1.2      ✔ lubridate 1.8.0 
    ## ✔ purrr     0.3.4      
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readr)
library(readxl)
library(tidyr)
```

# Problem 1

#### read in data

``` r
original <- read_csv(file = "./NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% janitor::clean_names()
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

-   clean data

``` r
nyc_transit <- original %>%
  select(line, station_name, station_latitude:entry, vending, ada) %>%
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE))
head(nyc_transit)
```

    ## # A tibble: 6 × 19
    ##   line  stati…¹ stati…² stati…³ route1 route2 route3 route4 route5 route6 route7
    ##   <chr> <chr>     <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  <chr> 
    ## 1 4 Av… 25th St    40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 2 4 Av… 25th St    40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 3 4 Av… 36th St    40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 4 4 Av… 36th St    40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 5 4 Av… 36th St    40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 6 4 Av… 45th St    40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>   <NA>  
    ## # … with 8 more variables: route8 <dbl>, route9 <dbl>, route10 <dbl>,
    ## #   route11 <dbl>, entrance_type <chr>, entry <lgl>, vending <chr>, ada <lgl>,
    ## #   and abbreviated variable names ¹​station_name, ²​station_latitude,
    ## #   ³​station_longitude

The original dataset contains 1868 rows and 32 columns, namely:
Division, Line, Station Name, Station Latitude, Station Longitude,
Route1, Route2, Route3, Route4, Route5, Route6, Route7, Route8, Route9,
Route10, Route11, Entrance Type, Entry, Exit Only, Vending, Staffing,
Staff Hours, ADA, ADA Notes, Free Crossover, North South Street, East
West Street, Corner, Entrance Latitude, Entrance Longitude, Station
Location and Entrance Location. Out of these variables, I retain line,
station, name, station latitude / longitude, routes served, entry,
vending, entrance type, and ADA compliance.

The cleaned dataset contains 1868 rows and 19 columns. For data
cleaning, I first clean the names of data using janitor package, then
only select the required variables, and change the entry variable from
character to logical variables. The data is not very clean because the
route variables can be further reorganized. At the same time, some ofthe
variable names contain double and have not been changed yet.

-   number of distinct station

``` r
nyc_transit %>%
  distinct(line, station_name) %>%
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

-   number of ADA compliant stations

``` r
nyc_transit %>%
  filter(ada == TRUE) %>%
  distinct(line, station_name) %>%
  nrow()
```

    ## [1] 84

There are 84 ADA compliant stations.

-   proportion of station entrances / exits without vending

``` r
nyc_transit %>%
  filter(vending == "NO") %>%
  pull(entry)%>%
  mean()
```

    ## [1] 0.3770492

There are 37.7% of the stations entrances / exits without vending.

-   number of stations serving A

``` r
# first change all the route names to character
refored_nyc_transit = mutate(nyc_transit,across(route1:route11, as.character))

refored_nyc_transit %>%
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct %>% 
  nrow()
```

    ## [1] 60

There are 60 stations serving A

-   A train with ADA compliant

``` r
refored_nyc_transit %>% 
  pivot_longer(route1:route11, names_to = "route_num", values_to = "route") %>%
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct() %>%
  nrow()
```

    ## [1] 17

There are 17 stations serving A with ADA compliant.
